/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_htc_eleven_multimediatesttool_NDKDemoActivity */

#ifndef _Included_com_htc_eleven_multimediatesttool_NDKDemoActivity
#define _Included_com_htc_eleven_multimediatesttool_NDKDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_htc_eleven_multimediatesttool_NDKDemoActivity
 * Method:    getNativeServiceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_htc_eleven_multimediatesttool_NDKDemoActivity_getNativeServiceName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
